stages:
    - test

pytest:
    stage: test
    image: "python:3.7"
    before_script:
        - pip install -r requirements.txt
    script:
        - cd app/
        - ls -a
        - python -m junitxml discover
    artifacts:
        when: always
        reports:
            junit: app/junit.xml
        expire_in: 2 weeks
