stages:
    - test

pytest:
    stage: test
    before_script:
        - sudo apt-get install python3-pip
        - pip3 install -r requirements.txt
    script:
        - cd app && python3 -m junitxml
    artifacts:
        when: always
        reports:
            junit: app/junit.xml
        expire_in: 2 weeks
