version: '3.7'

services:
  app:
    image: mqtt-wrapper:0.1
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
    - ./app:/app/src
  vernemq:
    image: vernemq/vernemq:1.12.3-alpine
    environment:
      DOCKER_VERNEMQ_ALLOW_ANONYMOUS: 'on'
      DOCKER_VERNEMQ_ACCEPT_EULA: 'yes'
    ports:
      - '8080:8080'
      - '1883:1883'